/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 28 15:50:53 GMT 2019
 */

package gun;

import org.junit.Test;
import static org.junit.Assert.*;
import gun.GunFactory;
import gun.GunState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GunFactory_ESTest extends GunFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GunState gunState0 = GunFactory.getGun(advancedRobot0);
      assertNull(gunState0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GunFactory gunFactory0 = new GunFactory();
  }
}
