/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 28 15:57:04 GMT 2019
 */

package visual;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import robocode.robotinterfaces.peer.IBasicRobotPeer;
import visual.RobotColour;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RobotColour_ESTest extends RobotColour_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      IBasicRobotPeer iBasicRobotPeer0 = mock(IBasicRobotPeer.class, new ViolatedAssumptionAnswer());
      advancedRobot0.setPeer(iBasicRobotPeer0);
      RobotColour robotColour0 = new RobotColour(advancedRobot0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RobotColour robotColour0 = null;
      try {
        robotColour0 = new RobotColour((AdvancedRobot) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("visual.RobotColour", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      RobotColour robotColour0 = null;
      try {
        robotColour0 = new RobotColour(advancedRobot0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // You cannot call the setColors() method before your run() method is called, or you are using a Robot object that the game doesn't know about.
         //
         verifyException("robocode._RobotBase", e);
      }
  }
}
