/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 28 15:56:09 GMT 2019
 */

package radar;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import radar.RadarFactory;
import radar.RadarState;
import robocode.AdvancedRobot;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RadarFactory_ESTest extends RadarFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      List<RadarState> list0 = RadarFactory.getRadar(advancedRobot0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RadarFactory radarFactory0 = new RadarFactory();
  }
}
