/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 28 15:57:53 GMT 2019
 */

package utils;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import utils.EnemyWave;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EnemyWave_ESTest extends EnemyWave_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EnemyWave enemyWave0 = new EnemyWave();
      assertEquals(0.0, enemyWave0.directAngle, 0.01);
  }
}
