/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 28 15:48:43 GMT 2019
 */

package utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import robocode.AdvancedRobot;
import utils.GFTWave;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GFTWave_ESTest extends GFTWave_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GFTWave gFTWave0 = new GFTWave((AdvancedRobot) null);
      gFTWave0.lateralDirection = (double) 13;
      Point2D.Float point2D_Float0 = new Point2D.Float();
      gFTWave0.gunLocation = (Point2D) point2D_Float0;
      gFTWave0.bearing = (-19.0);
      GFTWave.targetLocation = gFTWave0.gunLocation;
      // Undeclared exception!
      try { 
        gFTWave0.test();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("utils.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GFTWave gFTWave0 = new GFTWave(advancedRobot0);
      Point2D.Double point2D_Double0 = new Point2D.Double(0.0, 80);
      GFTWave.targetLocation = (Point2D) point2D_Double0;
      // Undeclared exception!
      try { 
        gFTWave0.test();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("utils.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GFTWave gFTWave0 = new GFTWave(advancedRobot0);
      gFTWave0.setSegmentations(0.7, 0.7, 0.7);
      assertEquals(0.0, gFTWave0.bearing, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GFTWave gFTWave0 = new GFTWave(advancedRobot0);
      gFTWave0.lateralDirection = (double) (-1031);
      // Undeclared exception!
      try { 
        gFTWave0.mostVisitedBearingOffset();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("utils.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GFTWave gFTWave0 = new GFTWave((AdvancedRobot) null);
      Point2D.Float point2D_Float0 = new Point2D.Float(80, 80);
      gFTWave0.gunLocation = (Point2D) point2D_Float0;
      gFTWave0.setSegmentations(0.0, 0.0, 0.0);
      gFTWave0.targetLocation = (Point2D) point2D_Float0;
      // Undeclared exception!
      try { 
        gFTWave0.test();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("utils.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AdvancedRobot advancedRobot0 = new AdvancedRobot();
      GFTWave gFTWave0 = new GFTWave(advancedRobot0);
      // Undeclared exception!
      try { 
        gFTWave0.setSegmentations(2465.31, 0.0, 900.0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 450
         //
         verifyException("utils.GFTWave", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GFTWave gFTWave0 = new GFTWave((AdvancedRobot) null);
      gFTWave0.bulletPower = (double) 13;
      Point2D.Float point2D_Float0 = new Point2D.Float();
      gFTWave0.gunLocation = (Point2D) point2D_Float0;
      GFTWave.targetLocation = gFTWave0.gunLocation;
      boolean boolean0 = gFTWave0.test();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GFTWave gFTWave0 = new GFTWave((AdvancedRobot) null);
      gFTWave0.setSegmentations(0.0, 0.0, 0.0);
      double double0 = gFTWave0.mostVisitedBearingOffset();
      assertEquals(0.0, double0, 0.01);
  }
}
